name: CI
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run notebooks
        run: |
          jupyter nbconvert --to notebook --execute */*.ipynb
